import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const goalsStyles = StyleSheet.create({
  layout: { width: '100%' },
  introRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: theme.spacing.xl,
    paddingBottom: theme.spacing.lg,
  },
  introRowMobile: { flexDirection: 'column', gap: theme.spacing.lg },
  introCopy: { flex: 1, minWidth: 0 },
  stepMeta: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.8,
    marginBottom: 12,
  },
  stepLabel: { color: theme.colors.mutedText },
  headline: {
    maxWidth: 620,
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 52,
    lineHeight: 49,
    letterSpacing: -0.4,
    textTransform: 'uppercase',
  },
  headlineMobile: { fontSize: 39, lineHeight: 38 },
  headingRule: {
    width: 64,
    height: 3,
    marginTop: 18,
    marginBottom: 16,
    overflow: 'hidden',
  },
  accentFill: { ...StyleSheet.absoluteFillObject },
  support: {
    maxWidth: 650,
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 14,
    lineHeight: 22,
  },
  reassurance: {
    flexBasis: 390,
    maxWidth: 430,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  reassuranceMobile: { flexBasis: 'auto', maxWidth: '100%' },
  reassuranceIcon: {
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 34,
    lineHeight: 36,
  },
  reassuranceCopy: { flex: 1, minWidth: 0 },
  reassuranceTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 14,
  },
  reassuranceBody: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 6,
  },
  goalsSection: {
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    paddingTop: theme.spacing.lg,
  },
  goalsBody: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.xl,
  },
  goalsBodyMobile: { flexDirection: 'column', gap: theme.spacing.lg },
  sectionCopy: { width: 270, minWidth: 220 },
  sectionCopyMobile: { width: '100%' },
  sectionTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  sectionHelper: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 6,
  },
  goalGrid: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.md,
  },
  goalGridMobile: { width: '100%', flexDirection: 'column' },
  goalCard: {
    width: '100%',
    minHeight: 118,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
    overflow: 'hidden',
  },
  goalCardHalf: { flexBasis: '47%', flexGrow: 1 },
  goalCardSelected: { borderWidth: 2, padding: theme.spacing.lg - 1 },
  goalCardPressed: { opacity: 0.82 },
  selectedWash: { ...StyleSheet.absoluteFillObject, opacity: 0.11 },
  goalSymbolRing: {
    width: 54,
    height: 54,
    borderWidth: 2,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goalSymbol: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 25,
  },
  goalCopy: { flex: 1, minWidth: 0 },
  goalLabel: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 22,
    lineHeight: 24,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  goalDescription: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  checkbox: {
    width: 25,
    height: 25,
    borderWidth: 1,
    borderColor: theme.colors.mutedText,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  checkboxMark: {
    color: theme.colors.white,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 14,
    zIndex: 1,
  },
  error: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    marginTop: theme.spacing.sm,
  },
});
