import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const mediaStepStyles = StyleSheet.create({
  layout: { width: '100%' },
  introRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'space-between',
    gap: theme.spacing.xl,
    paddingBottom: theme.spacing.lg,
  },
  introRowMobile: { flexDirection: 'column', gap: theme.spacing.lg },
  introCopy: { flex: 1, minWidth: 0 },
  stepMeta: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.8,
    marginBottom: 12,
  },
  stepLabel: { color: theme.colors.mutedText },
  headline: {
    maxWidth: 620,
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 52,
    lineHeight: 49,
    letterSpacing: -0.4,
    textTransform: 'uppercase',
  },
  headlineMobile: { fontSize: 39, lineHeight: 38 },
  headingRule: {
    width: 64,
    height: 3,
    marginTop: 18,
    marginBottom: 16,
    overflow: 'hidden',
  },
  accentFill: { ...StyleSheet.absoluteFillObject },
  support: {
    maxWidth: 650,
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 14,
    lineHeight: 22,
  },
  reassurance: {
    flexBasis: 390,
    maxWidth: 430,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.md,
    padding: theme.spacing.lg,
  },
  reassuranceMobile: { flexBasis: 'auto', maxWidth: '100%' },
  reassuranceIcon: {
    color: theme.colors.brandViolet,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 32,
  },
  reassuranceCopy: { flex: 1, minWidth: 0 },
  reassuranceTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 14,
  },
  reassuranceBody: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 6,
  },
  section: {
    width: '100%',
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.sm,
  },
  sectionMobile: { paddingTop: 20 },
  sectionColumns: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.xl,
  },
  sectionColumnsMobile: { flexDirection: 'column', gap: theme.spacing.lg },
  sectionCopy: { width: 270, minWidth: 220 },
  sectionCopyMobile: { width: '100%' },
  sectionContent: { flex: 1, minWidth: 0 },
  sectionTitleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  sectionTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 24,
    lineHeight: 26,
    letterSpacing: 0.7,
    textTransform: 'uppercase',
  },
  optional: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 1.2,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  sectionHelper: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 6,
  },
  bannerField: { marginBottom: 0 },
  connectionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.md },
  connectionCard: {
    flexGrow: 1,
    flexBasis: 290,
    minHeight: 118,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    flexDirection: 'row',
    alignItems: 'center',
    gap: theme.spacing.md,
    padding: theme.spacing.md,
  },
  urlConnectionCard: {
    flexGrow: 1,
    flexBasis: 280,
    minWidth: 240,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    padding: theme.spacing.md,
  },
  connectionIcon: {
    width: 46,
    height: 46,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.secondaryBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  connectionAvatar: { width: '100%', height: '100%' },
  connectionIconText: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 20,
  },
  connectionCopy: { flex: 1, minWidth: 0 },
  connectionProvider: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 0.7,
  },
  connectionDetail: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 11,
    marginTop: 3,
  },
  connectionLink: {
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 0.7,
    marginTop: 5,
  },
  connectionAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 },
  connectionActionText: {
    color: theme.colors.mutedText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 0.9,
  },
  connectionError: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 10,
    lineHeight: 16,
    marginTop: 6,
  },
  connectionInput: { marginTop: theme.spacing.sm, marginBottom: 0 },
  urlConnectionActions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  removeText: { color: theme.colors.error },
  disabled: { opacity: 0.42 },
  identityCard: {
    minHeight: 92,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  identityImage: { width: 90, height: 90, backgroundColor: theme.colors.secondaryBg },
  identityImageFallback: {
    width: 90,
    height: 90,
    backgroundColor: theme.colors.secondaryBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  identityFallbackText: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 9,
    letterSpacing: 1,
  },
  identityCopy: { flex: 1, minWidth: 0, paddingHorizontal: theme.spacing.md },
  identityName: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 13,
  },
  identityState: {
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 0.8,
    marginTop: 4,
  },
  identityActions: { alignItems: 'flex-end', paddingRight: theme.spacing.sm },
  identityResults: {
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    marginTop: theme.spacing.sm,
  },
  identityResult: {
    minHeight: 66,
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    flexDirection: 'row',
    alignItems: 'center',
  },
  identityResultImage: { width: 64, height: 64, backgroundColor: theme.colors.secondaryBg },
  identityThisIsMe: { minHeight: 64, justifyContent: 'center', paddingHorizontal: theme.spacing.md },
  spotifySearchAction: {
    minHeight: 44,
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.md,
  },
  websiteField: { marginBottom: 0 },
  tipsCard: {
    maxWidth: 620,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    padding: theme.spacing.lg,
    marginTop: theme.spacing.md,
  },
  tipsTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 13,
    letterSpacing: 0.4,
    marginBottom: theme.spacing.sm,
  },
  tip: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 19,
  },
  hydrationState: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
  },
  hydrationText: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 10,
    letterSpacing: 1,
  },
});
