import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: theme.colors.pageBg,
  },
  keyboardView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 32,
    paddingBottom: 48,
  },
  scrollContentMobile: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  pageFrame: {
    width: '100%',
    maxWidth: 1080,
    alignSelf: 'center',
  },
  header: {
    paddingBottom: 24,
  },
  headerBrandRow: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  personaLabel: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 2,
    textAlign: 'right',
  },
  headerRule: {
    height: 1,
    marginTop: 20,
    overflow: 'hidden',
  },
  accentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  progressDesktop: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.panelDivider,
  },
  progressAnnouncement: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  progressStep: {
    minWidth: 96,
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  progressConnector: {
    height: 1,
    flex: 1,
    minWidth: 18,
    backgroundColor: theme.colors.strongBorder,
    marginTop: 1,
  },
  progressNumber: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 1.2,
    marginBottom: 6,
  },
  progressMarker: {
    width: 22,
    height: 22,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  progressMarkerSkipped: {
    borderStyle: 'dashed',
  },
  markerAccentFill: {
    ...StyleSheet.absoluteFillObject,
  },
  progressMarkerText: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    zIndex: 1,
  },
  progressMarkerTextStrong: {
    color: theme.colors.white,
  },
  progressLabel: {
    color: theme.colors.disabledText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 1,
    marginTop: 7,
    textTransform: 'uppercase',
  },
  progressLabelActive: {
    color: theme.colors.primaryText,
  },
  progressMobile: {
    paddingTop: 16,
    paddingBottom: 22,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.panelDivider,
  },
  progressMobileCopy: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
  },
  progressCount: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1.5,
  },
  progressCurrentLabel: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.6,
  },
  progressSegments: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
  },
  progressSegmentButton: {
    flex: 1,
    minHeight: 44,
    justifyContent: 'center',
  },
  progressSegment: {
    height: 3,
    overflow: 'hidden',
  },
  progressSegmentState: {
    height: 16,
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    textAlign: 'center',
  },
  progressSegmentFuture: {
    backgroundColor: theme.colors.strongBorder,
  },
  main: {
    paddingTop: 48,
  },
  mainMobile: {
    paddingTop: 32,
  },
  stepMeta: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.8,
    marginBottom: 12,
  },
  stepHeading: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 54,
    lineHeight: 55,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  stepHeadingMobile: {
    fontSize: 42,
    lineHeight: 43,
  },
  headingRule: {
    width: 64,
    height: 3,
    marginTop: 18,
    marginBottom: 28,
    overflow: 'hidden',
  },
  placeholderPanel: {
    backgroundColor: theme.colors.elevatedSurface,
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    padding: 24,
  },
  placeholderEyebrow: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 1.7,
    marginBottom: 10,
  },
  placeholderTitle: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 30,
    lineHeight: 34,
    textTransform: 'uppercase',
  },
  placeholderBody: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 14,
    lineHeight: 22,
    maxWidth: 700,
    marginTop: 10,
  },
  confirmationControl: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    marginTop: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  confirmationControlError: {
    borderColor: theme.colors.error,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  checkboxMark: {
    color: theme.colors.white,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 14,
    zIndex: 1,
  },
  confirmationCopy: {
    flex: 1,
  },
  confirmationLabel: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.1,
  },
  confirmationHelp: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    marginTop: 3,
  },
  fieldError: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    marginTop: 8,
  },
  saveStatusPlaceholder: {
    minHeight: 38,
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginTop: 8,
  },
  saveStatus: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 1.5,
  },
  saveStatusFailed: {
    color: theme.colors.error,
  },
  errorPanel: {
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.error,
    backgroundColor: 'rgba(239, 68, 68, 0.07)',
    padding: 16,
    marginTop: 12,
  },
  errorTitle: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1,
  },
  errorMessage: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  retryButton: {
    minHeight: 44,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginTop: 6,
    paddingRight: 20,
  },
  retryButtonText: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.3,
  },
  footerDesktop: {
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    marginTop: 24,
    paddingTop: 24,
  },
  footerMobile: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    marginTop: 20,
    paddingTop: 20,
  },
  secondaryActions: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    marginTop: 10,
  },
  secondaryActionsDesktop: {
    flex: 1,
    maxWidth: 440,
    marginTop: 0,
  },
  secondaryAction: {
    minWidth: 112,
    minHeight: 44,
    justifyContent: 'center',
  },
  secondaryActionText: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.2,
  },
  continueButton: {
    width: 280,
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  continueButtonMobile: {
    width: '100%',
  },
  continueButtonText: {
    color: theme.colors.white,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 14,
    letterSpacing: 1.2,
    zIndex: 1,
  },
  actionDisabled: {
    opacity: 0.38,
  },
  readyBanner: {
    borderWidth: 1,
    borderColor: theme.colors.success,
    padding: 14,
    marginTop: 12,
  },
  readyText: {
    color: theme.colors.success,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 11,
    letterSpacing: 1.2,
  },
  statePage: {
    flex: 1,
    backgroundColor: theme.colors.pageBg,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statePanel: {
    width: '100%',
    maxWidth: 560,
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    backgroundColor: theme.colors.elevatedSurface,
    padding: 28,
  },
  stateEyebrow: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 10,
    letterSpacing: 1.8,
  },
  stateHeading: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 38,
    lineHeight: 40,
    marginTop: 10,
  },
  stateMessage: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 14,
    lineHeight: 22,
    marginTop: 10,
  },
  loadingBar: {
    height: 10,
    width: '72%',
    backgroundColor: theme.colors.inputBorder,
    marginTop: 18,
  },
  loadingBarShort: {
    width: '44%',
  },
  loadRetry: {
    minHeight: 48,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginTop: 16,
  },
  loadRetryText: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1.3,
  },
});
