import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
  showcase: {
    width: '100%',
    maxWidth: 850,
    minHeight: 420,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  showcaseCompact: {
    minHeight: 480,
    maxWidth: 340,
    alignItems: 'center',
  },
  glowBlue: {
    position: 'absolute',
    width: 250,
    height: 250,
    left: 90,
    bottom: 12,
    backgroundColor: theme.colors.brandBlue,
    opacity: 0.045,
    transform: [{ rotate: '34deg' }],
  },
  glowViolet: {
    position: 'absolute',
    width: 270,
    height: 270,
    right: 94,
    top: 8,
    backgroundColor: theme.colors.brandViolet,
    opacity: 0.045,
    transform: [{ rotate: '-28deg' }],
  },
  venueCard: {
    position: 'absolute',
    right: 18,
    top: 4,
  },
  venueCardCompact: {
    position: 'relative',
    right: 0,
    top: 0,
    alignSelf: 'flex-end',
  },
  artistCard: {
    position: 'absolute',
    left: 12,
    bottom: 2,
  },
  artistCardCompact: {
    position: 'relative',
    left: 0,
    bottom: 0,
    alignSelf: 'flex-start',
  },
  connectBadgeCompact: {
    width: 190,
    marginVertical: theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  connectBadgeDesktop: {
    position: 'absolute',
    left: 275,
    top: 258,
    zIndex: 2,
  },
  connectBadge: {
    width: 190,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    backgroundColor: theme.colors.overlaySurface,
    borderColor: theme.colors.mvpGoldBorder,
    borderWidth: 1,
    borderRadius: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 2, height: 3 },
    shadowOpacity: 0.28,
    shadowRadius: 2,
    elevation: 3,
  },
  connectLineLeft: {
    position: 'absolute',
    left: -24,
    top: 20,
    width: 24,
    height: 1,
    backgroundColor: theme.colors.brandBlue,
    opacity: 0.65,
  },
  connectLineRight: {
    position: 'absolute',
    right: -24,
    top: 20,
    width: 24,
    height: 1,
    backgroundColor: theme.colors.brandViolet,
    opacity: 0.65,
  },
  spark: {
    position: 'absolute',
    left: 11,
    top: 12,
    color: theme.colors.mvpGold,
    fontSize: 8,
  },
    spark2: {
        position: 'absolute',
        right: 11,
        top: 12,
        color: theme.colors.mvpGold,
        fontSize: 8,
},
  connectLabel: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    color: theme.colors.mvpGold,
    fontSize: theme.fontSizes.bodySmall,
    fontWeight: 'normal',
    letterSpacing: 1.6,
  },
  connectReasons: {
    fontFamily: theme.typography.fontFamily.bodyMedium,
    color: theme.colors.secondaryText,
    fontSize: 9,
    fontWeight: 'normal',
    letterSpacing: 0.6,
    marginTop: 4,
  },
});
