import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.pageBg,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: theme.spacing.xl,
  },
  pageFrame: {
    width: '100%',
    maxWidth: 1320,
    alignSelf: 'center',
  },
  logoRow: {
    paddingHorizontal: theme.spacing.xl,
    paddingTop: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  logoRowMobile: {
    paddingHorizontal: theme.spacing.lg,
  },
  header: {
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  headerDesktop: {
    alignItems: 'center',
    paddingHorizontal: 90,
    marginBottom: theme.spacing.sm,
  },
  eyebrow: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.caption,
    fontWeight: 'normal',
    letterSpacing: 2,
    marginBottom: theme.spacing.sm,
  },
  title: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 48,
    fontWeight: 'normal',
    lineHeight: 45,
    letterSpacing: -0.7,
    textAlign: 'center',
  },
  titleMobile: {
    fontSize: 38,
    lineHeight: 37,
  },
  subtitle: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: theme.fontSizes.bodyRegular,
    marginTop: theme.spacing.sm,
    textAlign: 'center',
  },
  carouselRegion: {
    position: 'relative',
    alignItems: 'center',
  },
  carouselControlRow: {
    width: '100%',
    maxWidth: 1040,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.xs,
    zIndex: 5,
  },
  carouselControl: {
    minWidth: 132,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.sm,
  },
  carouselControlNext: {
    justifyContent: 'flex-end',
  },
  carouselControlText: {
    color: theme.colors.mutedText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: theme.fontSizes.caption,
    fontWeight: 'normal',
    letterSpacing: 1.2,
  },
  carouselControlArrow: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.bodyLarge,
    marginHorizontal: theme.spacing.sm,
  },
  carouselControlArrowNext: {
    color: theme.colors.brandViolet,
  },
  carouselViewport: {
    position: 'relative',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  cardPosition: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sideCardHitTarget: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    minWidth: 44,
    zIndex: 4,
  },
  sideCardHitTargetPrevious: {
    left: 0,
  },
  sideCardHitTargetNext: {
    right: 0,
  },
  roleCard: {
    overflow: 'hidden',
    backgroundColor: theme.colors.elevatedSurface,
    borderWidth: 1,
    borderRadius: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.22,
    shadowRadius: 5,
    elevation: 4,
  },
  artistBorder: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 5,
  },
  roleImage: {
    height: '62%',
    justifyContent: 'space-between',
    padding: theme.spacing.md,
  },
  roleImageCrop: {
    backgroundColor: theme.colors.secondaryBg,
  },
  roleImageShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(6, 8, 12, 0.32)',
  },
  promoterTint: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(14, 165, 233, 0.13)',
  },
  roleImageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 18,
  },
  focusedRoleIdentifier: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  inactiveRoleHeader: {
    justifyContent: 'flex-start',
  },
  inactiveRoleHeaderPrevious: {
    justifyContent: 'flex-end',
  },
  roleIdentifier: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.caption,
    fontWeight: 'normal',
    letterSpacing: 1.6,
  },
  placeholderLabel: {
    color: theme.colors.mutedText,
    fontFamily: theme.typography.fontFamily.bodyMedium,
    fontSize: 8,
    fontWeight: 'normal',
    letterSpacing: 1,
    paddingHorizontal: 6,
    paddingVertical: 4,
    backgroundColor: 'rgba(12, 14, 19, 0.74)',
  },
  roleHero: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 48,
    fontWeight: 'normal',
    lineHeight: 43,
    letterSpacing: -0.5,
  },
  inactiveRoleHero: {
    maxWidth: 180,
  },
  inactiveRoleHeroPrevious: {
    alignSelf: 'flex-end',
    textAlign: 'right',
  },
  roleDescriptionArea: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.lg,
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
  },
  roleDescription: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: theme.fontSizes.bodyRegular,
    fontWeight: 'normal',
    lineHeight: 21,
  },
  roleCta: {
    minHeight: 62,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    borderTopWidth: 1,
    backgroundColor: '#11141a',
  },
  artistCta: {
    borderTopWidth: 0,
    paddingHorizontal: 0,
  },
  artistCtaArtwork: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  roleCtaText: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.bodySmall,
    fontWeight: 'normal',
    letterSpacing: 1.2,
  },
  roleCtaArrow: {
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.bodyLarge,
  },
  networkIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: theme.spacing.md,
  },
  networkLine: {
    width: 54,
    height: 1,
    marginHorizontal: -8,
    backgroundColor: theme.colors.panelDivider,
  },
  nodeHitTarget: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  networkNode: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.pageBg,
  },
  gestureCue: {
    color: theme.colors.disabledText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: theme.fontSizes.caption,
    fontWeight: 'normal',
    letterSpacing: 1.4,
    textAlign: 'center',
    marginTop: -4,
  },
  loginPrompt: {
    alignItems: 'center',
    marginTop: theme.spacing.md,
  },
  loginPromptText: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyMedium,
    fontSize: theme.fontSizes.caption,
    fontWeight: 'normal',
    letterSpacing: 1.2,
  },
  signInHitTarget: {
    minWidth: 96,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginLink: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: theme.fontSizes.bodySmall,
    fontWeight: 'normal',
    letterSpacing: 1,
  },
});
