import { StyleSheet } from 'react-native';
import { theme } from '../../theme/theme';

export const fieldStyles = StyleSheet.create({
  fieldGroup: {
    width: '100%',
    marginBottom: theme.spacing.lg,
  },
  label: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 11,
    letterSpacing: 1.25,
    marginBottom: theme.spacing.sm,
    textTransform: 'uppercase',
  },
  required: {
    color: theme.colors.error,
  },
  optional: {
    color: theme.colors.secondaryText,
    fontSize: 9,
    letterSpacing: 1.1,
  },
  helper: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: theme.spacing.xs,
  },
  error: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: theme.spacing.xs,
  },
  textareaContainer: {
    alignItems: 'flex-start',
    minHeight: 132,
  },
  textareaInput: {
    minHeight: 130,
    paddingTop: 14,
    textAlignVertical: 'top',
  },
  characterCount: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 11,
    marginTop: theme.spacing.xs,
    textAlign: 'right',
  },
  inputAdornment: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 13,
  },
  optionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  chip: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipSelected: {
    borderColor: theme.colors.brandBlue,
    backgroundColor: 'rgba(14, 165, 233, 0.12)',
  },
  chipUnavailable: {
    opacity: 0.38,
  },
  chipText: {
    color: theme.colors.mutedText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  chipTextSelected: {
    color: theme.colors.warmWhite,
  },
  limitText: {
    color: theme.colors.warning,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 10,
    letterSpacing: 0.8,
    marginTop: theme.spacing.sm,
  },
  choicesColumn: {
    gap: theme.spacing.sm,
  },
  choicesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  choiceCard: {
    minHeight: 56,
    minWidth: 136,
    borderWidth: 1,
    borderColor: theme.colors.strongBorder,
    backgroundColor: theme.colors.elevatedSurface,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 12,
  },
  choiceCardRow: {
    flexGrow: 1,
    flexBasis: 160,
  },
  choiceCardSelected: {
    borderColor: theme.colors.brandBlue,
    backgroundColor: 'rgba(14, 165, 233, 0.1)',
  },
  choiceLabel: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 12,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  choiceDescription: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  locationSuggestions: {
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: theme.colors.inputBorder,
    backgroundColor: theme.colors.elevatedSurface,
  },
  locationSuggestion: {
    minHeight: 48,
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    justifyContent: 'center',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
  },
  locationSuggestionText: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 13,
  },
  statusText: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 11,
    marginTop: 6,
  },
  locationAttribution: {
    color: theme.colors.secondaryText,
    fontSize: 12,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 8,
    textAlign: 'right',
  },
  locationFieldRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  locationFieldGrow: {
    flex: 1,
    minWidth: 150,
  },
  locationFieldCompact: {
    width: 116,
  },
  uploader: {
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    backgroundColor: theme.colors.elevatedSurface,
    minHeight: 176,
    overflow: 'hidden',
  },
  uploaderCompact: {
    minHeight: 0,
  },
  uploaderError: {
    borderColor: theme.colors.error,
  },
  preview: {
    width: '100%',
    minHeight: 150,
    backgroundColor: theme.colors.secondaryBg,
  },
  previewCompact: {
    minHeight: 0,
  },
  uploaderEmpty: {
    minHeight: 174,
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.lg,
  },
  uploaderEmptyCompact: {
    minHeight: 138,
    padding: theme.spacing.md,
  },
  uploaderTitle: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayBold,
    fontSize: 24,
    letterSpacing: 0.4,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  uploaderTitleCompact: {
    fontSize: 20,
  },
  uploaderCopy: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    lineHeight: 18,
    marginTop: 6,
    textAlign: 'center',
  },
  uploaderActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: 10,
  },
  uploaderStatus: {
    paddingHorizontal: theme.spacing.md,
    marginTop: 10,
  },
  textAction: {
    minHeight: 44,
    justifyContent: 'center',
    paddingRight: theme.spacing.md,
  },
  textActionLabel: {
    color: theme.colors.brandBlue,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 11,
    letterSpacing: 1,
  },
  removeActionLabel: {
    color: theme.colors.error,
  },
  progressTrack: {
    height: 3,
    backgroundColor: theme.colors.inputBorder,
  },
  progressFill: {
    height: 3,
    backgroundColor: theme.colors.brandBlue,
  },
  galleryList: {
    gap: theme.spacing.md,
  },
  galleryOrderActions: {
    flexDirection: 'row',
    gap: theme.spacing.md,
  },
  suggestionPanel: {
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.brandViolet,
    backgroundColor: theme.colors.elevatedSurface,
    padding: theme.spacing.md,
    gap: theme.spacing.sm,
  },
  suggestionRow: {
    borderTopWidth: 1,
    borderTopColor: theme.colors.panelDivider,
    paddingTop: theme.spacing.sm,
  },
  suggestionOrigin: {
    color: theme.colors.brandViolet,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 1,
  },
  suggestionLabel: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 13,
    marginTop: 3,
  },
  suggestionState: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 10,
    letterSpacing: 0.7,
    marginTop: 2,
  },
  suggestionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.md,
    marginTop: 4,
  },
  socialCard: {
    borderWidth: 1,
    borderColor: theme.colors.inputBorder,
    backgroundColor: theme.colors.elevatedSurface,
    padding: theme.spacing.md,
  },
  socialHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.md,
  },
  socialProvider: {
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  socialStatus: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 9,
    letterSpacing: 0.8,
  },
  socialIdentity: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 14,
    marginTop: 12,
  },
  socialDetail: {
    color: theme.colors.secondaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    marginTop: 4,
  },
});
