package com.mint.onboarding.taxonomy;

public enum GenreCode {
    ALTERNATIVE, BLUES, CLASSICAL, COUNTRY, ELECTRONIC, FOLK, FUNK, GOSPEL,
    HIP_HOP, INDIE, JAZZ, LATIN, METAL, POP, PUNK, R_AND_B, REGGAE, ROCK,
    SOUL, WORLD, EXPERIMENTAL, SINGER_SONGWRITER
}
