package com.mint.onboarding.taxonomy;

public enum VibeCode {
    ENERGETIC, INTIMATE, RAW, MELLOW, DARK, DREAMY, ATMOSPHERIC, EXPERIMENTAL,
    SOPHISTICATED, GRITTY, UPBEAT, HEAVY, GROOVY, ORGANIC, THEATRICAL
}
