import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';
import { APP_CONTENT_MAX_WIDTH } from './appLayout';

export const styles = StyleSheet.create({
  shell: { flex: 1, minHeight: 0, backgroundColor: theme.colors.pageBg, overflow: 'hidden' },
  header: { flexShrink: 0, width: '100%', backgroundColor: theme.colors.pageBg, zIndex: 2 },
  rail: { width: '100%', maxWidth: APP_CONTENT_MAX_WIDTH, alignSelf: 'center', minWidth: 0 },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  headerDivider: { height: 1, backgroundColor: theme.colors.panelDivider },
  left: { flexDirection: 'row', alignItems: 'center', gap: 24, flexShrink: 0 },
  leftCompact: { gap: 8 },
  control: { minHeight: 48, borderWidth: 1, borderColor: 'transparent', borderRadius: 3,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  logo: { minHeight: 48, flexShrink: 0 },
  nav: { paddingHorizontal: 12, borderColor: theme.colors.subtleBorder },
  navCompact: { paddingHorizontal: 5, gap: 4 },
  account: { minWidth: 48, maxWidth: 330, flexShrink: 1 },
  accountCompact: { width: 50, flexShrink: 0 },
  accountIcon: { width: 44, height: 44, flexShrink: 0, borderWidth: 1, borderRadius: 3,
    borderColor: theme.colors.subtleBorder, alignItems: 'center', justifyContent: 'center' },
  label: { fontFamily: theme.typography.fontFamily.bodyBold, fontSize: 14,
    color: theme.colors.primaryText, letterSpacing: 0.7 },
  chevron: { fontFamily: theme.typography.fontFamily.bodyBold, fontSize: 12, color: theme.colors.secondaryText },
  accountName: { flexShrink: 1, maxWidth: 230, minWidth: 0 },
  avatar: { width: 48, height: 48, flexShrink: 0, borderWidth: 1, borderColor: theme.colors.inputBorder,
    backgroundColor: theme.colors.elevatedSurface, alignItems: 'center', justifyContent: 'center' },
  initials: { fontFamily: theme.typography.fontFamily.displayBold, fontSize: 24, color: theme.colors.warmWhite },
  hovered: { backgroundColor: theme.colors.tagSurface },
  focused: { borderColor: theme.colors.brandBlue },
  pressed: { opacity: 0.7 },
  content: { flex: 1, minHeight: 0, zIndex: 0 },
  overlay: { ...StyleSheet.absoluteFillObject, zIndex: 1, pointerEvents: 'box-none' },
  menu: { position: 'absolute', backgroundColor: theme.colors.overlaySurface,
    borderWidth: 1, borderColor: theme.colors.strongBorder, paddingVertical: 8 },
  menuRow: { minHeight: 48, paddingHorizontal: 16, justifyContent: 'flex-start', borderRadius: 0 },
  menuText: { fontFamily: theme.typography.fontFamily.bodyMedium, fontSize: 14, color: theme.colors.primaryText },
  menuIdentity: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, paddingTop: 8 },
  identityCopy: { flex: 1, minWidth: 0 },
  identityName: { fontFamily: theme.typography.fontFamily.bodyBold, fontSize: 14, color: theme.colors.primaryText },
  persona: { fontFamily: theme.typography.fontFamily.bodyBold, fontSize: 10, letterSpacing: 1.4,
    color: theme.colors.secondaryText, marginTop: 4 },
  divider: { height: 1, backgroundColor: theme.colors.panelDivider, marginBottom: 8 },
});
