import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.primaryBg,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: theme.colors.primaryBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcomeCard: {
    backgroundColor: theme.colors.secondaryBg,
    margin: theme.spacing.md,
    padding: theme.spacing.lg,
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  welcomeEmoji: {
    fontSize: 48,
    marginBottom: theme.spacing.sm,
  },
  welcomeTitle: {
    fontSize: theme.fontSizes.h2,
    fontWeight: 'bold',
    color: theme.colors.primaryText,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: theme.fontSizes.bodyRegular,
    color: theme.colors.secondaryText,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  statCard: {
    flex: 1,
    backgroundColor: theme.colors.secondaryBg,
    marginHorizontal: theme.spacing.xs,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  statNumber: {
    fontSize: theme.fontSizes.h2,
    fontWeight: 'bold',
    color: theme.colors.primaryAccent,
  },
  statLabel: {
    fontSize: theme.fontSizes.caption,
    color: theme.colors.secondaryText,
    marginTop: theme.spacing.xs,
  },
  section: {
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  sectionTitle: {
    fontSize: theme.fontSizes.h3,
    fontWeight: 'bold',
    color: theme.colors.primaryText,
  },
  sectionCount: {
    fontSize: theme.fontSizes.bodySmall,
    color: theme.colors.primaryAccent,
  },
  matchCard: {
    backgroundColor: theme.colors.secondaryBg,
    padding: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    marginBottom: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  matchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.xs,
  },
  venueName: {
    fontSize: theme.fontSizes.bodyLarge,
    fontWeight: '600',
    color: theme.colors.primaryText,
    flex: 1,
  },
  matchBadge: {
    backgroundColor: theme.colors.primaryAccent + '33',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.round,
  },
  matchBadgeText: {
    fontSize: theme.fontSizes.caption,
    color: theme.colors.primaryAccent,
    fontWeight: '600',
  },
  venueMeta: {
    fontSize: theme.fontSizes.bodySmall,
    color: theme.colors.secondaryText,
    marginTop: 2,
  },
  ambienceRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: theme.spacing.sm,
  },
  ambienceTag: {
    backgroundColor: theme.colors.tertiaryBg || '#333',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 2,
    borderRadius: theme.borderRadius.sm,
    marginRight: theme.spacing.xs,
    marginBottom: theme.spacing.xs,
  },
  ambienceText: {
    fontSize: theme.fontSizes.caption,
    color: theme.colors.secondaryText,
  },
  emptyCard: {
    backgroundColor: theme.colors.secondaryBg,
    padding: theme.spacing.xl,
    borderRadius: theme.borderRadius.lg,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  emptyEmoji: {
    fontSize: 40,
    marginBottom: theme.spacing.md,
  },
  emptyTitle: {
    fontSize: theme.fontSizes.h3,
    fontWeight: 'bold',
    color: theme.colors.primaryText,
    marginBottom: theme.spacing.sm,
  },
  emptyText: {
    fontSize: theme.fontSizes.bodyRegular,
    color: theme.colors.secondaryText,
    textAlign: 'center',
    marginBottom: theme.spacing.lg,
  },
  emptyButton: {
    backgroundColor: theme.colors.primaryAccent,
    paddingVertical: theme.spacing.sm,
    paddingHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.md,
  },
  emptyButtonText: {
    color: theme.colors.white,
    fontWeight: '600',
    fontSize: theme.fontSizes.bodyRegular,
  },
  actionsSection: {
    paddingHorizontal: theme.spacing.md,
    paddingBottom: theme.spacing.xxl,
  },
  primaryButton: {
    backgroundColor: theme.colors.primaryAccent,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  primaryButtonText: {
    color: theme.colors.white,
    fontWeight: '600',
    fontSize: theme.fontSizes.bodyLarge,
  },
  secondaryButton: {
    backgroundColor: theme.colors.secondaryBg,
    paddingVertical: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.primaryAccent,
  },
  secondaryButtonText: {
    color: theme.colors.primaryAccent,
    fontWeight: '600',
    fontSize: theme.fontSizes.bodyLarge,
  },
});
