import { StyleSheet } from 'react-native';
import { theme } from '../theme/theme';

export const welcomeStyles = StyleSheet.create({
  screen: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#000000',
    overflow: 'hidden',
  },
  intro: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#000000',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
  finalScene: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#10051f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  background: { ...StyleSheet.absoluteFillObject },
  backgroundImage: { width: '100%', height: '100%' },
  center: {
    width: '100%',
    maxWidth: 840,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    zIndex: 1,
  },
  centerMobile: { paddingHorizontal: 24 },
  centerShort: { transform: [{ scale: 0.86 }] },
  logoWrap: { marginBottom: 24 },
  rule: { width: 210, height: 3, marginBottom: 36, overflow: 'hidden' },
  brandGradient: { ...StyleSheet.absoluteFillObject },
  heading: {
    width: '100%',
    color: theme.colors.warmWhite,
    fontFamily: theme.typography.fontFamily.displayExtraBold,
    fontSize: 68,
    lineHeight: 70,
    letterSpacing: 2.2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  headingMobile: { fontSize: 34, lineHeight: 38, letterSpacing: 0.8 },
  subtitle: {
    color: theme.colors.primaryText,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 22,
    lineHeight: 32,
    letterSpacing: 7,
    textAlign: 'center',
    marginTop: 20,
  },
  subtitleMobile: { fontSize: 16, lineHeight: 25, letterSpacing: 3.6 },
  enterButton: {
    width: 320,
    maxWidth: '100%',
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 52,
    overflow: 'hidden',
  },
  enterButtonSurface: {
    position: 'absolute',
    top: 2,
    right: 2,
    bottom: 2,
    left: 2,
    backgroundColor: 'rgba(20, 7, 43, 0.88)',
  },
  enterPressed: { opacity: 0.78 },
  enterDisabled: { opacity: 0.42 },
  enterText: {
    color: theme.colors.white,
    fontFamily: theme.typography.fontFamily.bodyBold,
    fontSize: 15,
    letterSpacing: 3,
    zIndex: 1,
  },
  tagline: {
    color: '#b8a6d9',
    fontFamily: theme.typography.fontFamily.bodySemiBold,
    fontSize: 10,
    letterSpacing: 4,
    textAlign: 'center',
    marginTop: 76,
  },
  taglineMobile: { fontSize: 8, letterSpacing: 2.8, marginTop: 54 },
  loadError: {
    color: theme.colors.error,
    fontFamily: theme.typography.fontFamily.bodyRegular,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 12,
  },
});
